name: Base CI Script

on:
  - push

jobs:
  xml-validate:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prerequisites Installation
        run: |
          apk add -U libxml2-utils g++ libstdc++ cmake make xerces-c-dev

      - name: Schema Validation
        run: |
          xmllint --noout --schema schema.xsd example_rules.xml

      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          make
          make install
